name: Full DevOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Utilisation de l'Action Composite Locale
      - name: Setup Tools via Composite Action
        uses: ./.github/actions/setup-tools
        with:
          install-terraform: 'true'
          terraform-version: '1.7.0'

      # Remplacement de l'action Trivy qui plantait précédemment (Correction master ou v0.29.0)
      - name: Run Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  # Appel du Workflow Réutilisable Docker
  build:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: devops-app
      context: ./app

        # Stage 3 : Scan de sécurité
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan application files
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'app/'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'table'

  deploy-staging:
    needs: security
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploying
        run: echo "Deploying to staging environment..."

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use secrets safely
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Secrets are masked in logs"
          echo "DB_PASSWORD length: ${#DB_PASSWORD}"
          echo "Deploying to production environment..."